
lista = []

try:
    print("Ingrese un numero")
    numero1 = int(input())
    lista.append(numero1)
    print("Ingrese un numero")
    numero2 = int(input())
    lista.append(numero2)
    print("Ingrese un numero")
    numero3 = int(input())
    lista.append(numero3)
    print("Ingrese un numero")
    numero4 = int(input())
    lista.append(numero4)
    print("Ingrese un numero")
    numero5 = int(input())
    lista.append(numero5)
    print("Ingrese un numero")
    numero6 = int(input())
    lista.append(numero6)
    print("Ingrese un numero")
    numero7 = int(input())
    lista.append(numero7)
    print("Ingrese un numero")
    numero8 = int(input())
    lista.append(numero8)
    print("Ingrese un numero")
    numero9 = int(input())
    lista.append(numero9)
    print("Ingrese un numero")
    numero10 = int(input())
    lista.append(numero10)

    suma = sum(lista)
    promedio = (suma / 10)
    print("")
    print("Suma total de todos los numeros ingresados:" , suma )
    print("")
    print("El promedio es de:" , promedio)
    print("")
except ValueError:
    print("Ingrese un caracter valido")